version: 2
updates:
- package-ecosystem: docker
  directory: "/alpine/3.10"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/alpine/3.11"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/traefik/2.0"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
